trigger:
  - main

pool:
  name: 'WindowsPrivateAgent'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: |
    dotnet --info
    dotnet build
    dotnet publish -c Release -o "$(Build.ArtifactStagingDirectory)"
  displayName: 'Build and Publish API'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure-Subscription'
    appType: webApp
    appName: 'DessertAppStatsAPI'
    package: "$(Build.ArtifactStagingDirectory)"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Call to API and generate new content from README.md
      $url = "https://dessertappstatsapi-ccg6eagqgkhkgpcf.brazilsouth-01.azurewebsites.net/api/pipelines/pipelines"
      $headers = @{
          "Authorization" = "Basic $(ConvertTo-SecureString -String :$(GITHUB_PERSONAL_ACCESS_TOKEN) -AsPlainText -Force)"
      }
      
      # Perform GET request to fetch data
      $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get

      # Inicialize README.md content
      $readmeContent = "<h1>Last Succeeded Pipelines:History</h1><br /><br />"

      # Verify if response has content
      if ($response -ne $null -and $response.Count -gt 0) {
          $response | ForEach-Object {
          # Fetch some details in the request
          $readmeContent += "<h2>Pipeline ID:$($_.id)</h2><br />"
          $readmeContent += "<p><strong>Build Number:</strong> $($_.buildNumber)</p><br />"
          $readmeContent += "<p><strong>Status:</strong> $($_.status)</p><br />"
          $readmeContent += "<p><strong>Result:</strong> $($_.result)</p><br />"
          $readmeContent += "<p><strong>Finish Time:</strong> $($_.finishTime)</p><br /><br />"
      }
      } else {
          Write-Output "There are nothing to show"
      }

      # Show generated content
      Write-Output "Pipelines content:"
      Write-Output $readmeContent

      #Write retrieved information in the README.md
      Set-Content -Path "$(Build.SourcesDirectory)/README.md" -Value $readmeContent
  displayName: 'Generate updated README.md with pipeline stats'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "jhonfredylopezarenas@gmail.com"
      git config --global user.name "jhonl2002"
      git clone https://$env:GITHUB_PAT@github.com/JhonL2002/DessertApp.git
      cd DessertApp
      Move-Item -Path ../README.md -Destination ./README.md -Force
      git add README.md
      git commit -m "Updated README with latest pipeline stats"
      git push
  env:
    GITHUB_PAT: $(GITHUB_PERSONAL_ACCESS_TOKEN)
  displayName: 'Push updated README.md to DessertApp repository'
